CREATE OR REPLACE STAGE s3_stage
URL='s3://ecommerce-data-lake/processed/'
CREDENTIALS=(AWS_KEY_ID='****' AWS_SECRET_KEY='****');

COPY INTO RAW.ORDERS
FROM @s3_stage/orders
FILE_FORMAT = (TYPE = PARQUET);

COPY INTO RAW.PRODUCTS
FROM @s3_stage/products
FILE_FORMAT = (TYPE = PARQUET);
