CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE OR REPLACE TABLE RAW.ORDERS (
  order_id STRING,
  customer_id STRING,
  product_id STRING,
  order_date DATE,
  amount NUMBER
);

CREATE OR REPLACE TABLE RAW.PRODUCTS (
  product_id STRING,
  product_name STRING,
  category STRING,
  price NUMBER
);
