version: 2

models:
  - name: stg_orders
    description: "Raw orders staging"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null

  - name: stg_customers
    description: "Raw customers staging"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
